server:
  port: 5050

spring:
  application:
    name: stock-flow-api
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5051}/${POSTGRES_DB:db-stockflow}
    username: ${POSTGRES_USER:gustavo}
    password: ${POSTGRES_PASSWORD:123456}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:5052}/realms/${KEYCLOAK_REALM:stock-flow-realm}

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:5052}
  realm: ${KEYCLOAK_REALM:stock-flow-realm}
  client-id: ${KEYCLOAK_CLIENT_ID:stock-flow-api}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

