package com.gustavosdaniel.stock_flow_api.domain.enums;

/**
 * Enumerates the types of alerts that can be generated by the system.
 * <p>
 * Each type corresponds to a specific stock status condition that triggers
 * a notification, such as a product running out of stock or exceeding its
 * maximum quantity.
 * </p>
 */
public enum NotificationType {

    OUT_OF_STOCK,
    STOCK_LOW,
    REORDER_POINT,
    OVERSTOCK
}
