limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

server {
    listen 80;
    server_name api.stockflow.gustavosdaniel.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /health {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.stockflow.gustavosdaniel.com;

    ssl_certificate /etc/letsencrypt/live/api.stockflow.gustavosdaniel.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.stockflow.gustavosdaniel.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # O DNS interno do Docker
    resolver 127.0.0.11 valid=30s ipv6=off;

    # 1. Rota do Keycloak (Prioridade para /auth/)
    location /auth/ {
        set $auth_host keycloak:8080;
        proxy_pass http://$auth_host;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
    }

    # 2. SSE — sem buffering para notificações
    location /api/v1/notifications/stream {
        set $api_host stockflow-api:6060;
        proxy_pass http://$api_host;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
    }

    # 3. Rota geral da sua API Spring Boot
    location / {
        limit_req zone=api_limit burst=20 nodelay;
        set $api_host stockflow-api:6060;
        proxy_pass http://$api_host;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}